defaults:
  - train_transform: simple
  - test_transform: simple
  - unlabeled_transform: simple
  # - color_jitter: color_jitter
  # - random_crop: random_crop
  # - random_erasing: random_erasing
  # - random_flip: random_flip
  # - random_gaussian_noise: random_gaussian_noise
  # - random_rotation: random_rotation

num_classes: 48
batch_size: 240
num_workers: 0
train_path: ${data_dir}/train_mean_teacher
test_path: ${data_dir}/train
unlabeled_path: ${data_dir}/unlabelled