defaults:
  - _self_
  - model: resnet
  - dataset: 10_classes_supervised
  - optim: adamw
  - loss_fn: cross_entropy

epochs: 10
pseudo_epochs: 5
num_pseudo_epochs: 1
no_augmentation: true

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

# To create training sets and test sets
datasetmodule:
  _target_: data.datasetmodule.DatasetModule
  train_dataset_path: ${dataset.train_path}
  train_transform: ${dataset.train_transform}
  unlabelled_dataset_path: ${dataset.unlabelled_path}
  unlabelled_transform: ${dataset.unlabelled_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/datasetV2
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/model.pt
checkpoint_before_pseudo_path: ${root_dir}/checkpoints/model_before_pseudo_label.pt
wandb_name: run_pseudolabel

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true