defaults:
  - _self_
  - model: vit
  - dataset: 10_classes_supervised
  - optim: adamw
  - loss_fn: cross_entropy

epochs: 8
pseudo_epochs: 15
num_pseudo_epochs: 5
list_pseudo_epochs: [4,4,5,5,6,6,7,7,8,9,10,11,12,15,25]
no_augmentation: true
batch_size: ${dataset.batch_size}
labeled_batch_size: 62
num_workers: ${dataset.num_workers}

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

# To create training sets and test sets
datasetmodule:
  _target_: data.datasetmodule.DatasetModule
  train_dataset_path: ${dataset.train_path}
  train_transform: ${dataset.train_transform}
  unlabeled_dataset_path: ${dataset.unlabeled_path}
  unlabeled_transform: ${dataset.unlabeled_transform}
  test_dataset_path: ${dataset.test_path}
  test_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/datasetV2
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/model_clip_list.pt
checkpoint_before_pseudo_path: ${root_dir}/checkpoints/model_before_pseudo_label_clip_list.pt
wandb_name: run_clip_list_vit

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true